name: validator
version: 0.0.1
author: Karan Goel <karan@goel.io>
description: String validation and sanitization for Dart
homepage: https://github.com/karan/tvalidator.dart
documentation: https://github.com/karan/tvalidator.dart
